### PR TITLE
Updates, Gradle build, and collection of fixes from the network of forks

### PR DESCRIPTION
**Pull request by rpavlik**
I'm not sure how much time you have to still maintain this - I suspect very little - but I did put in some work a while back to collect the best changes from the various forks, as well as simplify/improve the build and try to reduce the number of "vendored" JAR dependencies. I can now build with Gradle, and the distributions created contain a launcher that runs well.

Despite the substantial improvements, I haven't bumped the version to avoid stepping on your toes if you were to do a future release. If you aren't planning on doing much future release, you might want to at least release these changes as a 3.3.1 so that they can be used with a modern Java version, etc.

(BTW - it has CI now even, with snapshot builds uploaded and everything!)

### CODE REVIEW

**Comment by unquietwiki** [comment]
Hey @rpavlik . I just found this software tonight.

1. I saw the JRE in the installer is ancient. This appears to work with the [OpenJ9 version of JRE8](https://adoptopenjdk.net/releases.html?variant=openjdk8&jvmVariant=openj9): can you verify with your collection of fixes?
2. Have you run any of this through [code linters](https://awesome-linters.hugomartins.io/#java)? They're decent at flagging stuff that might be a problem; been using such to identify potential issues with Bash, C, and Python code.

**Comment by rpavlik** [comment]
I don't use the installer - I just use the bundle on Linux with my system JRE. I actually have very little Java experience, so no, I have not run any linters on it. (I'm big on static analysis so the fact I haven't done this is rather surprising :D )  I'm sure there's plenty of low-hanging fruit. If nothing else, there's a ton of code that's just commented out instead of being removed - don't know if there's a tool for removing that in Java like there is in Python.

**Comment by cStuartHardwick** [comment]
Hi Ryan;

I'd like to take a look as your version and among other things, debug the category search if it hasn't already been done. I'm a seasoned coder, but never in this environment. Can you point me to a document describing the tools and steps needed to pull and compile and create the installer?

**Comment by rpavlik** [comment]
I have a new branch rebased on the recent changes that got merged: https://github.com/rpavlik/VUE/tree/vue4-rebase

Frankly, what I have done is just clone it and open it in Android Studio. Gradle is used for the build, which Android Studio supports. Alternately you can use whatever editor you like and just do `./gradlew assemble` to build stuff from the command line. I think I have the readme updated in my fork.

**Comment by rpavlik** [comment]
Replaced by #57

**Pull request closed without merging**
